#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinycssloaders)
library(tidyverse)
library(httr)
library(lubridate)
library(plotly)
library(leaflet)
library(shinyjs)
library(viridis)
library(mapview)
library(RColorBrewer)

# Define UI for application that draws a histogram
shinyUI(
  navbarPage(title = div(div(id = 'user-name', textOutput('full_name')),
                         div(id = 'user-name', uiOutput('log_link')),
                         div(id = 'logo-id',img(src="NPTlogos2.png", height = "70px")),
                         tags$a("DFRM Home",href = 'http://www.nptfisheries.org')

                         ),
             id = "kus_navbar",
             windowTitle = "DFRM-Kus",
             theme = "styles.css",
             position = "fixed-top",
             collapsible = TRUE,
             footer = div(id = "footer-id",
                          "The data presented in the Kus web application is not solely collected, managed or owned
                          by the Nez Perce Tribe. All data should be considered draft and is not guaranteed for
                          accuracy.  Permission to use the data should be sought from the original collectors."),
             
             tabPanel("Kus Home",
                      useShinyjs(),   # include Shiny JS
                      fluidPage(
                        #fluidRow(div(id = 'header-id',"KUS")),
                        h2('Department of Fisheries Resources Management'),
                        h3('Data Summaries, Analyses and Visualizations'),
                        fluidRow(
                          column(12, leafletOutput('redd_map', height = 690, width = "100%"))
                        ),
                        fluidRow(
                          column(12,
                            helpText('The Kus web application is intended to provide near real-time data summaries and
                                      visualizations for Department of Fisheries Resources Management staff and to
                                      support Snake Basin fisheries management decisions. The tools also creates easy access to
                                      valuable fish information for general public consumption and informs Nez Perce
                                      Tribal members of the most current and best fishing oppurtunities.',  
#                                       Nez Perce Tribal members and designed to Centralized Data Management System (CDMS) and Shiny 
#                                       applications are designed to support advanced data acquisition, data storage and management,
#                                      data integration, data mining, and data visualization.  Additionally, the purpose of this
#                                      system is to ultimately facilitate secure, redundant storage, maintenance, and efficient
#                                      exchange of science-based information generated by NPT DFRM while preserving data integrity.
#                                      As a result, this system increases DFRM’s capacity to support individual and regional
#                                      reporting, collaborative analyses, and informed policy and management decisions.
#                                      All this is accomplished by utilizing standardized performance measures as recommended
#                                      by the Ad Hoc Supplementation Work Group (Beasley et al. 2008).',
                                     width = '100%')
                            )
                        )
                        # fluidRow(
                        #   column(12, withSpinner(plotlyOutput('home_river')))
                        # ),
                        # hr(),
                        # fluidRow(
                        #   column(6, withSpinner(plotlyOutput('home_BONwin', height = 800))),
                        #   column(6, withSpinner(plotlyOutput('home_LGRwin', height = 800)))
                        # ),
                        # hr(),
                        # fluidRow(
                        #   column(12, withSpinner(plotlyOutput('home_redd')))
                        # )
                      )
              ),
              navbarMenu("Summarized Data",
                       tabPanel("Snake Basin Populaiton Indicators and Metrics",
                                sidebarLayout(
                                  sidebarPanel(
                                    style = "position:fixed;width:25%",
                                    width = 3,
                                    fluidRow(column(12, leafletOutput('MPGmap', height = 700, width = '100%')))
                                    ),
                                  mainPanel(
                                    titlePanel('Population Indicators and Metrics'),
                                    fluidPage(
                                      fluidRow(column(12, textOutput('MPGfilter')))
                                    )#column(12, offset = 0, withSpinner(DT::dataTableOutput("mpg_table"))))
                                  )
                                  )
                                ),
                       tabPanel("Spawning Ground Surveys",
                               sidebarLayout(
                                   sidebarPanel(
                                     style = "position:fixed;width:15%;",
                                     width = 2,
                                          uiOutput("streams_menu"), 
                                          actionButton("summ_reset", label = "Refresh", class = "mybutton",
                                                       position = 'center', width = '100%'),
                                     helpText('Select Streams and click "Refresh" to populate Summary Tables.')
                                   ),
                                 mainPanel(
                                    titlePanel('Spawning Ground Surveys: Redd and Carcass Summaries'),
                                    fluidPage(
                                      fluidRow(column(12, withSpinner(plotlyOutput(outputId = 'sgs1', height = 400, width = '120%')))),
                                      fluidRow(
                                               splitLayout(cellWidths = c('40%', '40%', '40%'), 
                                                           withSpinner(plotlyOutput(outputId = 'sgs2', height = 300)),
                                                           withSpinner(plotlyOutput(outputId = 'sgs3', height = 300, width = '100%')),
                                                           withSpinner(plotlyOutput(outputId = 'sgs4', height = 300 )))
                                             ),                                      
                                      fluidRow(column(12, offset = 0, withSpinner(DT::dataTableOutput("summ_table"))))
                                    )
                                  )
                                )
                              ),
                      tabPanel("Juvenile Metrics",
                        sidebarLayout(
                          sidebarPanel(
                            style = "position:fixed;width:22%",
                            width = 3,
                            fluidRow(column(12, helpText("Click a pin to populate Graphs and Summary Table."))),
                            fluidRow(column(12, leafletOutput('RSTmap', height = 500, width = '100%')))
                            ),
                          mainPanel(
                            fluidPage(
                               titlePanel('Juvenile Metrics: Abundance and Survival'),
                               br(),
                               fluidRow(
                                        column(6, plotlyOutput('juv_sum1', height = 500)),
                                        column(6, plotlyOutput('juv_sum2', height = 500))                                        ),
                               hr(),
                               fluidRow(column(12, offset = 0, DT::dataTableOutput("rstsumm_table")))
                            )
                          )
                        )
                      ),
                      tabPanel("Weir Returns"),
                      tabPanel("Hydro-system Conditions and Fish Counts",
                               uiOutput("year_menu"),
                               actionButton("year_submit", "Query River Data", class = 'mybutton'),
                               withSpinner(plotOutput("river_plot")),
                               uiOutput("river_menu"),
                               withSpinner(plotOutput("window_plot")),
                               uiOutput("spp_menu")
                               )
             ),
             navbarMenu("Fish Management",
                        tabPanel(tags$a("In-season Snake Basin Management")),
                        tabPanel(tags$a("Hydro-system Operations", href = "https://nptfisheries.shinyapps.io/pitph2/")),
                        tabPanel(tags$a("PITtrackR", href = "https://nptfisheries.shinyapps.io/PITtrackR/"))
                        ),
             tabPanel("Raw Data", id = 'raw_data', value = 'tab_rawdata',
                      fluidPage(
                          fluidRow(
                                column(3, uiOutput("raw_dataset_menu"))
                            ),
                          fluidRow(
                            column(6, helpText("Select the desired dataset then the project, stream and locations of interest and click submit query.")),
                            column(2, offset = 2, align = "center",
                                   actionButton("raw_submit", label = "Submit Query", class = "mybutton")),
                            column(2, align = "center",
                                   downloadButton("raw_export", label = "Export .CSV File", class = "mybutton"))
                            )
                        ),
                      hr(),
                      withSpinner(DT::dataTableOutput("raw_table"))
                ),
             navbarMenu("Data Entry", menuName = 'data_entry',
                        tabPanel(tags$a("CDMS - Project Data Entry", href = "https://cdms.nptfisheries.org/index.html#/projects")),
                        tabPanel(tags$a("LSRCP FINS", href = "https://www.finsnet.org/"))
                        )
  ) # close navbarPage
) # close shinyUI
